import tree
import treeplotter
dataset, labels = tree.createdataset()
#shannon = tree.calcshannonent(dataset)
#print(shannon)
#res = tree.splitdataset(dataset, 1, 1)
#print(res)
#res = tree.choosebestfeaturetosplit(dataset)
#print(res)
#mytree = tree.createtree(dataset,labels)
#print(mytree)
#treeplotter.creataplot()
mytree = treeplotter.retrievetree(0)
#print(mytree)
#mytree = treeplotter.retrievetree(1)
#print(mytree)
#print(treeplotter.getnumleafs(mytree))
#print(treeplotter.gettreedepth(mytree))
print(treeplotter.classfy(mytree, labels, [1, 0]))